name: Setup C env

runs:
  using: composite

  steps:
    - name: Setup MSYS2
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-protobuf
          mingw-w64-x86_64-yaml-cpp

    - name: Setup Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          ninja-build \
          libprotobuf-dev \
          protobuf-compiler \
          protobuf-compiler-grpc \
          libyaml-cpp-dev \
          libx11-dev \
          libxext-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxi-dev \
          libxinerama-dev \
          libxss-dev \
          libxtst-dev \
          libwayland-dev \
          wayland-protocols \
          libdecor-0-dev \
          libgl-dev \
          libopengl-dev \
          libglx-dev \
          libegl1-mesa-dev \
          libdrm-dev \
          libgbm-dev \
          libpulse-dev \
          libasound2-dev \
          libusb-1.0-0-dev \
          libudev-dev \
          libunwind-dev \
          libfribidi-dev \
          libthai-dev \
          libprotobuf-dev
          
    - name: Setup CMake(Linux)
      if: runner.os == 'Linux'
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: 4.3.0
        ninjaVersion: 1.13.2

    - name: Setup macOS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install \
          cmake \
          ninja \
          protobuf \
          yaml-cpp
