name: Build External

runs:
  using: composite

  steps:
    - name: Calculate cache key
      id: external-key
      shell: bash
      run: |
        hash=$(
          {
            git ls-tree HEAD external/bgfx | awk '{print $3}'
            git ls-tree HEAD external/bx | awk '{print $3}'
            git ls-tree HEAD external/bimg | awk '{print $3}'
            git ls-tree HEAD external/bgfx.cmake | awk '{print $3}'
            git ls-tree HEAD external/SDL | awk '{print $3}'
            git ls-tree HEAD external/SDL-image | awk '{print $3}'
            sha256sum external/CMakeLists.txt
          } | sha256sum | cut -d' ' -f1
        )
        key="external-${{ runner.os }}-${{ runner.arch }}-${hash}"
        echo "key=$key" >> "$GITHUB_OUTPUT"


    - name: Restore external cache
      id: external-cache
      uses: actions/cache/restore@v4
      with:
        path: external/install/release
        key: ${{ steps.external-key.outputs.key }}

    - name: Build external (Windows)
      if: steps.external-cache.outputs.cache-hit != 'true' && runner.os == 'Windows'
      shell: msys2 {0}
      run: |
        cmake -S external -B external/build -G Ninja
        cmake --build external/build --parallel

    - name: Build external (Unix)
      if: steps.external-cache.outputs.cache-hit != 'true' && runner.os != 'Windows'
      shell: bash
      run: |
        cmake -S external -B external/build -G Ninja
        cmake --build external/build --parallel

    - name: Save external cache
      if: steps.external-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: external/install/release
        key: ${{ steps.external-key.outputs.key }}
