name: Build Project

runs:
  using: composite
  
  steps:
    - name: get submodules
      uses: ./.github/actions/getSubmodules

    - name: Checkout assets
      shell: bash
      run: |
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        git submodule update --init resources/assets


    - name: Setup env
      uses: ./.github/actions/setupCENV


    - name: Build external
      uses: ./.github/actions/buildExternal
    
    - name: Configure
      if: runner.os != 'Windows'
      shell: bash
      run: |
        cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

    - name: Configure Windows
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: |
        cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

    - name: Build
      if: runner.os != 'Windows'
      shell: bash
      run: |
        cmake --build build --parallel

    - name: Build Windows
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: |
        cmake --build build --parallel
