# mediapipe-tasks-c.nuitka-package.config.yml
- module-name: 'mediapipe'
  dlls:
    - from_filenames:
        relative_path: 'tasks/c'
        prefixes:
          - 'libmediapipe'
        suffixes:
          - 'dll'
      when: 'win32'
    - from_filenames:
        relative_path: 'tasks/c'
        prefixes:
          - 'libmediapipe'
        suffixes:
          - 'so'
      when: 'linux'
    - from_filenames:
        relative_path: 'tasks/c'
        prefixes:
          - 'libmediapipe'
        suffixes:
          - 'dylib'
      when: 'macos'
