name: Build

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Calculate external cache key
        id: external-key
        uses: ./.github/actions/external-cache-key

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_image

      - name: Restore bgfx cache
        id: bgfx-cache
        uses: actions/cache/restore@v4
        with:
          path: external/install/release
          key: ${{ steps.external-key.outputs.key }}

      - name: Build external
        if: steps.bgfx-cache.outputs.cache-hit != 'true'
        shell: msys2 {0}
        run: |
          cmake -S external -B external/build -G Ninja
          cmake --build external/build --parallel

      - name: Save bgfx cache
        if: steps.bgfx-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: external/install/release
          key: ${{ steps.external-key.outputs.key }}

      - name: Configure
        shell: msys2 {0}
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        shell: msys2 {0}
        run: |
          cmake --build build --parallel
      