name: Release

on:
  push:
    tags:
      - 'release-*'
    branches:
      - ci/github-actions

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Project
        uses: ./.github/actions/buildProject

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-${{ runner.os }}-${{ runner.arch }}
          path: build/

      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: hello_world.py



      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: dist-${{ runner.os }}-${{ runner.arch }}
      #     path: build/dist/
