name: Release

on:
  push:
    tags:
      - 'release-*'

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Project
        uses: ./.github/actions/buildProject

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: scalix-windows
          path: build/Release/
